Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -95,22 +95,14 @@ jobs:
         echo "NEW_REVISION=$NEW_REVISION" >> $GITHUB_OUTPUT
     - name: Deploy service
       run: |
-        REVISION=${{ steps.register-task.outputs.NEW_REVISION }}
-        if aws ecs list-services --cluster ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} \
-          | jq -r '.serviceArns[]' | grep -q "${{ env.SERVICE_NAME }}"; then
-          echo "Updating existing service..."
-          aws ecs update-service \
-            --cluster ${{ env.CLUSTER_NAME }} \
-            --service-name ${{ env.SERVICE_NAME }} \
-            --task-definition ${{ env.TASK_FAMILY }}:$REVISION \
-            --force-new-deployment \
-            --region ${{ env.AWS_REGION }}
-        else
+        SERVICE_EXISTS=$(aws ecs list-services --cluster ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} | jq -r '.serviceArns[] | contains("'${{ env.SERVICE_NAME }}'")' | grep -q "true" && echo "EXISTS" || echo "MISSING")
+        
+        if [ "$SERVICE_EXISTS" = "MISSING" ]; then
           echo "Creating new service..."
           aws ecs create-service \
             --cluster ${{ env.CLUSTER_NAME }} \
             --service-name ${{ env.SERVICE_NAME }} \
-            --task-definition ${{ env.TASK_FAMILY }}:$REVISION \
+            --task-definition ${{ env.TASK_FAMILY }}:${{ steps.register-task.outputs.NEW_REVISION }} \
             --desired-count 1 \
             --launch-type FARGATE \
             --network-configuration '{
@@ -121,8 +113,15 @@ jobs:
               }
             }' \
             --region ${{ env.AWS_REGION }}
+        else
+          echo "Updating existing service..."
+          aws ecs update-service \
+            --cluster ${{ env.CLUSTER_NAME }} \
+            --service-name ${{ env.SERVICE_NAME }} \
+            --task-definition ${{ env.TASK_FAMILY }}:${{ steps.register-task.outputs.NEW_REVISION }} \
+            --force-new-deployment \
+            --region ${{ env.AWS_REGION }}
         fi
-
 
     - name: Wait for deployment
       run: |
